name: absensi_example
version: 1.0.8+10
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  carousel_slider: 4.0.0
  # google_fonts: 2.3.1
  google_fonts: ^4.0.0
  http: 0.13.4
  # http: ^1.0.0
  get_storage: 2.0.3
  google_maps_flutter: ^2.1.2
  # geolocator: 8.2.0
  geolocator: ^9.0.2
  table_calendar: 3.0.4
  syncfusion_flutter_calendar: 19.4.56
  intl: 0.17.0
  image_picker: 0.8.4+11
  geocoding: 2.0.4
  datetime_picker_formfield: 2.0.0
  onesignal_flutter: 3.3.2
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  get_it: ^7.2.0
  flutter_polyline_points: ^1.0.0
  flutter_otp_text_field: ^1.1.0+2
  flutter_countdown_timer: ^4.1.0
  # camera: ^0.9.2+1
  camera: ^0.10.3+2
  # google_ml_vision: ^0.0.7
  google_ml_vision: ^0.0.8
  # path_provider: ^2.0.0
  path_provider: ^2.0.14
  # path_provider: ^2.0.12
  # tflite_flutter: ^0.7.0
  # tflite_flutter: ^0.9.0
  path: ^1.8.2
  image: ^3.1.1
  # image: ^4.0.13
  platform: ^3.1.0
  flutter_neumorphic: ^3.2.0
  # unique_identifier: ^0.3.0
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.11.0
  flutter_secure_storage: ^8.0.0
  new_version: ^0.3.1
  device_info_plus: ^8.1.0
  flutter_easyloading: ^3.0.5
  file: ^6.1.4
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_absen_rsp.png"

flutter:
  assets:
    - assets/slider/
    - assets/images/
    - assets/mobilefacenet.tflite
  uses-material-design: true
